<?php
/** @var $block \SportStore\CustomerFeedback\Block\Adminhtml\FeedbackDetailsBlock */
?>
<table class="data-grid">
    <thead>
        <tr>
            <th class="data-grid-th"><?= __('ID'); ?></th>
            <th class="data-grid-th"><?= __('First name'); ?></th>
            <th class="data-grid-th"><?= __('Last name'); ?></th>
            <th class="data-grid-th"><?= __('Age'); ?></th>
            <th class="data-grid-th"><?= __('Email'); ?></th>
            <th class="data-grid-th"><?= __('Title'); ?></th>
            <th class="data-grid-th"><?= __('Message'); ?></th>
            <th class="data-grid-th"><?= __('Status'); ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> <?= $block->getModel()->getId(); ?></td>
            <td> <?= $block->getModel()->getFirstname(); ?></td>
            <td> <?= $block->getModel()->getLastname(); ?></td>
            <td> <?= $block->getModel()->getAge(); ?></td>
            <td> <?= $block->getModel()->getEmail(); ?></td>
            <td> <?= $block->getModel()->getTitle(); ?></td>
            <td> <?= $block->getModel()->getMessage(); ?></td>
            <td> <?= $block->getModel()->getStatus(); ?></td>
        </tr>
    </tbody>
</table>
